from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
from openpyxl import Workbook
import os
import re
import html as ihtml
import pandas as pd
import requests
import json

service_current = Service(r"F:\_Python\messin\chromedriver.exe")
options = Options()
options.binary_location = r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
options.add_argument("log-level=3")
options.add_argument("--ignore-certificate-error")
options.add_argument("--ignore-ssl-errors")
wb= Workbook()
ws=wb.active

def scraper(drvr, champ):
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    driver.get(drvr)
    content = driver.page_source
    bestmatchups = []
    worstmatchups = []
    takeoutlist = '1', '2', '3', '4', '5', '6', '7', '8', '9', '.', 'WR', '%', ',', 'games'

    words_format = r'\b(?:{})\b'.format('|'.join(takeoutlist))
    remove_words = lambda y: re.sub(words_format, ' ', y)
    words_format2 = r'\d'.format('|'.join(takeoutlist))
    remove_words2 = lambda y: re.sub(words_format2, ' ', y)
    words_format3 = r'\W'.format('|'.join(takeoutlist))
    remove_words3 = lambda y: re.sub(words_format3, ' ', y)
    words_format4 = r'WR'.format('|'.join(takeoutlist))
    remove_words4 = lambda y: re.sub(words_format4, ' ', y)

    soup = BeautifulSoup(content, features="html.parser")
    for element in soup.findAll(attrs={'class': 'counters-list best-win-rate'}):
        best = element.findAll('a')
        for bestfinal in best:
            bestmatchups.append(bestfinal.text)

    bestmatchups2 = list(map(remove_words, bestmatchups))
    bestmatchups3 = list(map(remove_words2, bestmatchups2))
    bestmatchups4 = list(map(remove_words3, bestmatchups3))
    bestmatchups5 = list(map(remove_words4, bestmatchups4))
    bestmatchups6 = [item.strip() for item in bestmatchups5]

    for element in soup.findAll(attrs={'class': 'counters-list worst-win-rate'}):
        worst = element.findAll('a')
        for worstfinal in worst:
            worstmatchups.append(worstfinal.text)

    worstmatchups2 = list(map(remove_words, worstmatchups))
    worstmatchups3 = list(map(remove_words2, worstmatchups2))
    worstmatchups4 = list(map(remove_words3, worstmatchups3))
    worstmatchups5 = list(map(remove_words4, worstmatchups4))
    worstmatchups6 = [item.strip() for item in worstmatchups5]

    dfsetup1 = {'Best Matchups':bestmatchups6,'Worst Matchups':worstmatchups6}
    dfsetup2 = pd.DataFrame.from_dict(dfsetup1)
    with pd.ExcelWriter("F:\_Python\messin\matchups.xlsx", engine="openpyxl", mode='a',  if_sheet_exists="replace") as writer:
        dfsetup2.to_excel(writer, sheet_name=champ, index=False)

scraper('https://u.gg/lol/champions/aatrox/counter?rank=overall', 'aatrox')
scraper('https://u.gg/lol/champions/ahri/counter?rank=overall', 'ahri')
scraper('https://u.gg/lol/champions/akali/counter?rank=overall', 'akali')
scraper('https://u.gg/lol/champions/akshan/counter?rank=overall', 'akshan')
scraper('https://u.gg/lol/champions/alistar/counter?rank=overall', 'alistar')
scraper('https://u.gg/lol/champions/amumu/counter?rank=overall', 'amumu')
scraper('https://u.gg/lol/champions/anivia/counter?rank=overall', 'anivia')
scraper('https://u.gg/lol/champions/annie/counter?rank=overall', 'annie')
scraper('https://u.gg/lol/champions/aphelios/counter?rank=overall', 'aphelios')
scraper('https://u.gg/lol/champions/ashe/counter?rank=overall', 'ashe')
scraper('https://u.gg/lol/champions/aurelionsol/counter?rank=overall', 'aurelionsol')
scraper('https://u.gg/lol/champions/azir/counter?rank=overall', 'azir')
scraper('https://u.gg/lol/champions/bard/counter?rank=overall', 'bard')
scraper('https://u.gg/lol/champions/belveth/counter?rank=overall', 'belveth')
scraper('https://u.gg/lol/champions/blitzcrank/counter?rank=overall', 'blitzcrank')
scraper('https://u.gg/lol/champions/brand/counter?rank=overall', 'brand')
scraper('https://u.gg/lol/champions/braum/counter?rank=overall', 'braum')
scraper('https://u.gg/lol/champions/caitlyn/counter?rank=overall', 'caitlyn')
scraper('https://u.gg/lol/champions/camille/counter?rank=overall', 'camille')
scraper('https://u.gg/lol/champions/cassiopeia/counter?rank=overall', 'cassiopeia')
scraper('https://u.gg/lol/champions/chogath/counter?rank=overall', 'chogath')
scraper('https://u.gg/lol/champions/corki/counter?rank=overall', 'corki')
scraper('https://u.gg/lol/champions/darius/counter?rank=overall', 'darius')
scraper('https://u.gg/lol/champions/diana/counter?rank=overall', 'diana')
scraper('https://u.gg/lol/champions/mundo/counter?rank=overall', 'mundo')
scraper('https://u.gg/lol/champions/draven/counter?rank=overall', 'draven')
scraper('https://u.gg/lol/champions/ekko/counter?rank=overall', 'ekko')
scraper('https://u.gg/lol/champions/elise/counter?rank=overall', 'elise')
scraper('https://u.gg/lol/champions/evelynn/counter?rank=overall', 'evelynn')
scraper('https://u.gg/lol/champions/ezreal/counter?rank=overall', 'ezreal')
scraper('https://u.gg/lol/champions/fiddlesticks/counter?rank=overall', 'fiddlesticks')
scraper('https://u.gg/lol/champions/fiora/counter?rank=overall', 'fiora')
scraper('https://u.gg/lol/champions/fizz/counter?rank=overall', 'fizz')
scraper('https://u.gg/lol/champions/galio/counter?rank=overall', 'galio')
scraper('https://u.gg/lol/champions/gangplank/counter?rank=overall', 'gangplank')
scraper('https://u.gg/lol/champions/garen/counter?rank=overall', 'garen')
scraper('https://u.gg/lol/champions/gnar/counter?rank=overall', 'gnar')
scraper('https://u.gg/lol/champions/gragas/counter?rank=overall', 'gragas')
scraper('https://u.gg/lol/champions/graves/counter?rank=overall', 'graves')
scraper('https://u.gg/lol/champions/gwen/counter?rank=overall', 'gwen')
scraper('https://u.gg/lol/champions/hecarim/counter?rank=overall', 'hecarim')
scraper('https://u.gg/lol/champions/heimerdinger/counter?rank=overall', 'heimerdinger')
scraper('https://u.gg/lol/champions/illaoi/counter?rank=overall', 'illaoi')
scraper('https://u.gg/lol/champions/irelia/counter?rank=overall', 'irelia')
scraper('https://u.gg/lol/champions/ivern/counter?rank=overall', 'ivern')
scraper('https://u.gg/lol/champions/janna/counter?rank=overall', 'janna')
scraper('https://u.gg/lol/champions/jarvaniv/counter?rank=overall', 'jarvaniv')
scraper('https://u.gg/lol/champions/jax/counter?rank=overall', 'jax')
scraper('https://u.gg/lol/champions/jayce/counter?rank=overall', 'jayce')
scraper('https://u.gg/lol/champions/jhin/counter?rank=overall', 'jhin')
scraper('https://u.gg/lol/champions/jinx/counter?rank=overall', 'jinx')
scraper('https://u.gg/lol/champions/ksante/counter?rank=overall', 'ksante')
scraper('https://u.gg/lol/champions/kaisa/counter?rank=overall', 'kaisa')
scraper('https://u.gg/lol/champions/kalista/counter?rank=overall', 'kalista')
scraper('https://u.gg/lol/champions/karma/counter?rank=overall', 'karma')
scraper('https://u.gg/lol/champions/karthus/counter?rank=overall', 'karthus')
scraper('https://u.gg/lol/champions/kassadin/counter?rank=overall', 'kassadin')
scraper('https://u.gg/lol/champions/katarina/counter?rank=overall', 'katarina')
scraper('https://u.gg/lol/champions/kayle/counter?rank=overall', 'kayle')
scraper('https://u.gg/lol/champions/kayn/counter?rank=overall', 'kayn')
scraper('https://u.gg/lol/champions/kennen/counter?rank=overall', 'kennen')
scraper('https://u.gg/lol/champions/khazix/counter?rank=overall', 'khazix')
scraper('https://u.gg/lol/champions/kindred/counter?rank=overall', 'kindred')
scraper('https://u.gg/lol/champions/kled/counter?rank=overall', 'kled')
scraper('https://u.gg/lol/champions/kogmaw/counter?rank=overall', 'kogmaw')
scraper('https://u.gg/lol/champions/leblanc/counter?rank=overall', 'leblanc')
scraper('https://u.gg/lol/champions/leesin/counter?rank=overall', 'leesin')
scraper('https://u.gg/lol/champions/leona/counter?rank=overall', 'leona')
scraper('https://u.gg/lol/champions/lillia/counter?rank=overall', 'lillia')
scraper('https://u.gg/lol/champions/lissandra/counter?rank=overall', 'lissandra')
scraper('https://u.gg/lol/champions/lucian/counter?rank=overall', 'lucian')
scraper('https://u.gg/lol/champions/lulu/counter?rank=overall', 'lulu')
scraper('https://u.gg/lol/champions/lux/counter?rank=overall', 'lux')
scraper('https://u.gg/lol/champions/malphite/counter?rank=overall', 'malphite')
scraper('https://u.gg/lol/champions/malzahar/counter?rank=overall', 'malzahar')
scraper('https://u.gg/lol/champions/maokai/counter?rank=overall', 'maokai')
scraper('https://u.gg/lol/champions/masteryi/counter?rank=overall', 'masteryi')
scraper('https://u.gg/lol/champions/missfortune/counter?rank=overall', 'missfortune')
scraper('https://u.gg/lol/champions/mordekaiser/counter?rank=overall', 'mordekaiser')
scraper('https://u.gg/lol/champions/morgana/counter?rank=overall', 'morgana')
scraper('https://u.gg/lol/champions/nami/counter?rank=overall', 'nami')
scraper('https://u.gg/lol/champions/nasus/counter?rank=overall', 'nasus')
scraper('https://u.gg/lol/champions/nautilus/counter?rank=overall', 'nautilus')
scraper('https://u.gg/lol/champions/neeko/counter?rank=overall', 'neeko')
scraper('https://u.gg/lol/champions/nidalee/counter?rank=overall', 'nidalee')
scraper('https://u.gg/lol/champions/nilah/counter?rank=overall', 'nilah')
scraper('https://u.gg/lol/champions/nocturne/counter?rank=overall', 'nocturne')
scraper('https://u.gg/lol/champions/nunu/counter?rank=overall', 'nunu')
scraper('https://u.gg/lol/champions/olaf/counter?rank=overall', 'olaf')
scraper('https://u.gg/lol/champions/orianna/counter?rank=overall', 'orianna')
scraper('https://u.gg/lol/champions/ornn/counter?rank=overall', 'ornn')
scraper('https://u.gg/lol/champions/pantheon/counter?rank=overall', 'pantheon')
scraper('https://u.gg/lol/champions/poppy/counter?rank=overall', 'poppy')
scraper('https://u.gg/lol/champions/pyke/counter?rank=overall', 'pyke')
scraper('https://u.gg/lol/champions/qiyana/counter?rank=overall', 'qiyana')
scraper('https://u.gg/lol/champions/quinn/counter?rank=overall', 'quinn')
scraper('https://u.gg/lol/champions/rakan/counter?rank=overall', 'rakan')
scraper('https://u.gg/lol/champions/rammus/counter?rank=overall', 'rammus')
scraper('https://u.gg/lol/champions/reksai/counter?rank=overall', 'reksai')
scraper('https://u.gg/lol/champions/rell/counter?rank=overall', 'rell')
scraper('https://u.gg/lol/champions/renata/counter?rank=overall', 'renata')
scraper('https://u.gg/lol/champions/renekton/counter?rank=overall', 'renekton')
scraper('https://u.gg/lol/champions/rengar/counter?rank=overall', 'rengar')
scraper('https://u.gg/lol/champions/riven/counter?rank=overall', 'riven')
scraper('https://u.gg/lol/champions/rumble/counter?rank=overall', 'rumble')
scraper('https://u.gg/lol/champions/ryze/counter?rank=overall', 'ryze')
scraper('https://u.gg/lol/champions/samira/counter?rank=overall', 'samira')
scraper('https://u.gg/lol/champions/sejuani/counter?rank=overall', 'sejuani')
scraper('https://u.gg/lol/champions/senna/counter?rank=overall', 'senna')
scraper('https://u.gg/lol/champions/seraphine/counter?rank=overall', 'seraphine')
scraper('https://u.gg/lol/champions/sett/counter?rank=overall', 'sett')
scraper('https://u.gg/lol/champions/shaco/counter?rank=overall', 'shaco')
scraper('https://u.gg/lol/champions/shen/counter?rank=overall', 'shen')
scraper('https://u.gg/lol/champions/shyvana/counter?rank=overall', 'shyvana')
scraper('https://u.gg/lol/champions/singed/counter?rank=overall', 'singed')
scraper('https://u.gg/lol/champions/sion/counter?rank=overall', 'sion')
scraper('https://u.gg/lol/champions/sivir/counter?rank=overall', 'sivir')
scraper('https://u.gg/lol/champions/skarner/counter?rank=overall', 'skarner')
scraper('https://u.gg/lol/champions/sona/counter?rank=overall', 'sona')
scraper('https://u.gg/lol/champions/soraka/counter?rank=overall', 'soraka')
scraper('https://u.gg/lol/champions/swain/counter?rank=overall', 'swain')
scraper('https://u.gg/lol/champions/sylas/counter?rank=overall', 'sylas')
scraper('https://u.gg/lol/champions/syndra/counter?rank=overall', 'syndra')
scraper('https://u.gg/lol/champions/tahmkench/counter?rank=overall', 'tahmkench')
scraper('https://u.gg/lol/champions/taliyah/counter?rank=overall', 'taliyah')
scraper('https://u.gg/lol/champions/talon/counter?rank=overall', 'talon')
scraper('https://u.gg/lol/champions/taric/counter?rank=overall', 'taric')
scraper('https://u.gg/lol/champions/teemo/counter?rank=overall', 'teemo')
scraper('https://u.gg/lol/champions/thresh/counter?rank=overall', 'thresh')
scraper('https://u.gg/lol/champions/tristana/counter?rank=overall', 'tristana')
scraper('https://u.gg/lol/champions/trundle/counter?rank=overall', 'trundle')
scraper('https://u.gg/lol/champions/tryndamere/counter?rank=overall', 'tryndamere')
scraper('https://u.gg/lol/champions/twistedfate/counter?rank=overall', 'twistedfate')
scraper('https://u.gg/lol/champions/twitch/counter?rank=overall', 'twitch')
scraper('https://u.gg/lol/champions/udyr/counter?rank=overall', 'udyr')
scraper('https://u.gg/lol/champions/urgot/counter?rank=overall', 'urgot')
scraper('https://u.gg/lol/champions/varus/counter?rank=overall', 'varus')
scraper('https://u.gg/lol/champions/vayne/counter?rank=overall', 'vayne')
scraper('https://u.gg/lol/champions/veigar/counter?rank=overall', 'veigar')
scraper('https://u.gg/lol/champions/velkoz/counter?rank=overall', 'velkoz')
scraper('https://u.gg/lol/champions/vex/counter?rank=overall', 'vex')
scraper('https://u.gg/lol/champions/vi/counter?rank=overall', 'vi')
scraper('https://u.gg/lol/champions/viego/counter?rank=overall', 'viego')
scraper('https://u.gg/lol/champions/viktor/counter?rank=overall', 'viktor')
scraper('https://u.gg/lol/champions/vladimir/counter?rank=overall', 'vladimir')
scraper('https://u.gg/lol/champions/volibear/counter?rank=overall', 'volibear')
scraper('https://u.gg/lol/champions/warwick/counter?rank=overall', 'warwick')
scraper('https://u.gg/lol/champions/wukong/counter?rank=overall', 'wukong')
scraper('https://u.gg/lol/champions/xayah/counter?rank=overall', 'xayah')
scraper('https://u.gg/lol/champions/xerath/counter?rank=overall', 'xerath')
scraper('https://u.gg/lol/champions/xinzhao/counter?rank=overall', 'xinzhao')
scraper('https://u.gg/lol/champions/yasuo/counter?rank=overall', 'yasuo')
scraper('https://u.gg/lol/champions/yone/counter?rank=overall', 'yone')
scraper('https://u.gg/lol/champions/yorick/counter?rank=overall', 'yorick')
scraper('https://u.gg/lol/champions/yuumi/counter?rank=overall', 'yuumi')
scraper('https://u.gg/lol/champions/zac/counter?rank=overall', 'zac')
scraper('https://u.gg/lol/champions/zed/counter?rank=overall', 'zed')
scraper('https://u.gg/lol/champions/zeri/counter?rank=overall', 'zeri')
scraper('https://u.gg/lol/champions/ziggs/counter?rank=overall', 'ziggs')
scraper('https://u.gg/lol/champions/zilean/counter?rank=overall', 'zilean')
scraper('https://u.gg/lol/champions/zoe/counter?rank=overall', 'zoe')
scraper('https://u.gg/lol/champions/zyra/counter?rank=overall', 'zyra')
